repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-json
    -   id: check-yaml
        exclude: ^conda.recipe/
    -   id: end-of-file-fixer
        exclude_types: [csv]
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending
        exclude_types: [csv]
    -   id: sort-simple-yaml
    -   id: requirements-txt-fixer
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://github.com/PyCQA/pylint
    rev: v2.16.2
    hooks:
    -   id: pylint
