name: via-wind
channels:
    - conda-forge
    - nrel
dependencies:
    - python=3.10
    - numpy>=1.25.2,<2
    - tqdm>=4.66.1,<4.67
    - imageio>=2.31.1 ,<2.32
    - pandas>=2.1.0,<3
    - gdal>=3.7.1,<3.8
    - geopandas>=0.13.2,<0.15
    - pyogrio>=0.6.0,<0.7
    - rasterio>=1.3.8,<1.4
    - lxml>=4.9.3,<4.10
    - nrel-rex>=0.2.84,<0.3
    - click>=8.1.7,<8.2
    - statsmodels>=0.14.0,<0.15
    - pip>=23.2.1,<24
